/**
 * Comprehensive Bangalore Parking Locations & Zones Dataset
 * Provides realistic coordinates, capacity, rate tiers, and facilities across Bangalore.
 */

const BANGALORE_AREAS = [
  {
    id: "koramangala-5th-block",
    name: "Koramangala 5th Block",
    area: "Koramangala",
    zone: "South Bangalore",
    lat: 12.9279,
    lng: 77.6271,
    baseRate: 40,
    tier: "Premium",
    totalSlots: 24,
    hasEVCharging: true,
    address: "80 Feet Road, 5th Block, Koramangala, Bengaluru"
  },
  {
    id: "indiranagar-100ft",
    name: "Indiranagar 100ft Road",
    area: "Indiranagar",
    zone: "East Bangalore",
    lat: 12.9784,
    lng: 77.6408,
    baseRate: 50,
    tier: "Premium",
    totalSlots: 30,
    hasEVCharging: true,
    address: "100 Feet Road, HAL 2nd Stage, Indiranagar, Bengaluru"
  },
  {
    id: "whitefield-itpl",
    name: "ITPL Whitefield",
    area: "Whitefield",
    zone: "East Bangalore",
    lat: 12.9698,
    lng: 77.7500,
    baseRate: 40,
    tier: "Standard",
    totalSlots: 40,
    hasEVCharging: true,
    address: "International Tech Park, Whitefield Main Rd, Bengaluru"
  },
  {
    id: "mg-road-metro",
    name: "MG Road Metro Hub",
    area: "MG Road",
    zone: "Central Bangalore",
    lat: 12.9758,
    lng: 77.6097,
    baseRate: 60,
    tier: "Premium",
    totalSlots: 20,
    hasEVCharging: true,
    address: "Mahatma Gandhi Road, Near Metro Station, Bengaluru"
  },
  {
    id: "brigade-road",
    name: "Brigade Road Commercial Hub",
    area: "Brigade Road",
    zone: "Central Bangalore",
    lat: 12.9716,
    lng: 77.6099,
    baseRate: 60,
    tier: "Premium",
    totalSlots: 18,
    hasEVCharging: false,
    address: "Brigade Road, Shanthala Nagar, Ashok Nagar, Bengaluru"
  },
  {
    id: "ub-city",
    name: "UB City Luxury Plaza",
    area: "UB City",
    zone: "Central Bangalore",
    lat: 12.9719,
    lng: 77.5960,
    baseRate: 80,
    tier: "VIP",
    totalSlots: 35,
    hasEVCharging: true,
    address: "24, Vittal Mallya Rd, KG Halli, D' Souza Layout, Bengaluru"
  },
  {
    id: "jayanagar-4th-block",
    name: "Jayanagar 4th Block Complex",
    area: "Jayanagar",
    zone: "South Bangalore",
    lat: 12.9250,
    lng: 77.5938,
    baseRate: 30,
    tier: "Standard",
    totalSlots: 25,
    hasEVCharging: false,
    address: "4th Block, Jayanagar BDA Complex, Bengaluru"
  },
  {
    id: "electronic-city-p1",
    name: "Electronic City Phase 1",
    area: "Electronic City",
    zone: "South Bangalore",
    lat: 12.8399,
    lng: 77.6770,
    baseRate: 30,
    tier: "Standard",
    totalSlots: 50,
    hasEVCharging: true,
    address: "Hosur Road, Electronics City Phase 1, Bengaluru"
  },
  {
    id: "hsr-sector-1",
    name: "HSR Layout Sector 1",
    area: "HSR Layout",
    zone: "South-East Bangalore",
    lat: 12.9116,
    lng: 77.6474,
    baseRate: 30,
    tier: "Standard",
    totalSlots: 22,
    hasEVCharging: true,
    address: "27th Main Rd, Sector 1, HSR Layout, Bengaluru"
  },
  {
    id: "manyata-tech-park",
    name: "Manyata Embassy Business Park",
    area: "Hebbal",
    zone: "North Bangalore",
    lat: 13.0353,
    lng: 77.5972,
    baseRate: 40,
    tier: "Standard",
    totalSlots: 60,
    hasEVCharging: true,
    address: "Outer Ring Rd, Nagavara, Bengaluru"
  },
  {
    id: "marathahalli-bridge",
    name: "Marathahalli Multiplex Bay",
    area: "Marathahalli",
    zone: "East Bangalore",
    lat: 12.9591,
    lng: 77.6974,
    baseRate: 30,
    tier: "Standard",
    totalSlots: 28,
    hasEVCharging: false,
    address: "Varthur Rd, Marathahalli, Bengaluru"
  },
  {
    id: "bellandur-ecospace",
    name: "Ecospace Bellandur",
    area: "Bellandur",
    zone: "South-East Bangalore",
    lat: 12.9259,
    lng: 77.6762,
    baseRate: 40,
    tier: "Standard",
    totalSlots: 45,
    hasEVCharging: true,
    address: "Outer Ring Road, Bellandur, Bengaluru"
  },
  {
    id: "church-street",
    name: "Church Street Boulevard",
    area: "Church Street",
    zone: "Central Bangalore",
    lat: 12.9753,
    lng: 77.6072,
    baseRate: 50,
    tier: "Premium",
    totalSlots: 16,
    hasEVCharging: false,
    address: "Church Street, Shantala Nagar, Bengaluru"
  },
  {
    id: "malleshwaram-8th-cross",
    name: "Malleshwaram 8th Cross",
    area: "Malleshwaram",
    zone: "North-West Bangalore",
    lat: 13.0035,
    lng: 77.5680,
    baseRate: 30,
    tier: "Standard",
    totalSlots: 20,
    hasEVCharging: false,
    address: "8th Cross Rd, Malleshwaram, Bengaluru"
  },
  {
    id: "yelahanka-new-town",
    name: "Yelahanka New Town Central",
    area: "Yelahanka",
    zone: "North Bangalore",
    lat: 13.1005,
    lng: 77.5963,
    baseRate: 25,
    tier: "Economy",
    totalSlots: 30,
    hasEVCharging: true,
    address: "Major Sandeep Unnikrishnan Rd, Yelahanka, Bengaluru"
  },
  {
    id: "btm-layout-2nd-stage",
    name: "BTM Layout 2nd Stage",
    area: "BTM Layout",
    zone: "South Bangalore",
    lat: 12.9166,
    lng: 77.6101,
    baseRate: 30,
    tier: "Standard",
    totalSlots: 24,
    hasEVCharging: false,
    address: "7th Main Road, BTM 2nd Stage, Bengaluru"
  },
  {
    id: "banashankari-bda",
    name: "Banashankari BDA Complex",
    area: "Banashankari",
    zone: "South Bangalore",
    lat: 12.9255,
    lng: 77.5468,
    baseRate: 25,
    tier: "Economy",
    totalSlots: 20,
    hasEVCharging: false,
    address: "Banashankari 2nd Stage, Bengaluru"
  },
  {
    id: "jp-nagar-6th-phase",
    name: "JP Nagar Cultural Hub",
    area: "JP Nagar",
    zone: "South Bangalore",
    lat: 12.9063,
    lng: 77.5857,
    baseRate: 30,
    tier: "Standard",
    totalSlots: 22,
    hasEVCharging: true,
    address: "24th Main, JP Nagar 6th Phase, Bengaluru"
  },
  {
    id: "rajajinagar-orion",
    name: "Rajajinagar Orion Gateway",
    area: "Rajajinagar",
    zone: "West Bangalore",
    lat: 12.9916,
    lng: 77.5520,
    baseRate: 40,
    tier: "Premium",
    totalSlots: 32,
    hasEVCharging: true,
    address: "Dr Rajkumar Rd, Rajajinagar, Bengaluru"
  },
  {
    id: "basavanagudi-dvk",
    name: "Basavanagudi Gandhi Bazaar",
    area: "Basavanagudi",
    zone: "South Bangalore",
    lat: 12.9425,
    lng: 77.5742,
    baseRate: 30,
    tier: "Standard",
    totalSlots: 18,
    hasEVCharging: false,
    address: "Gandhi Bazaar Main Road, Basavanagudi, Bengaluru"
  },
  {
    id: "sarjapur-road-wipro",
    name: "Sarjapur Road Wipro Bay",
    area: "Sarjapur Road",
    zone: "East Bangalore",
    lat: 12.9121,
    lng: 77.6855,
    baseRate: 30,
    tier: "Standard",
    totalSlots: 36,
    hasEVCharging: true,
    address: "Sarjapur Main Rd, Doddakannelli, Bengaluru"
  },
  {
    id: "bannerghatta-gopalan",
    name: "Bannerghatta Road Mall Annex",
    area: "Bannerghatta",
    zone: "South Bangalore",
    lat: 12.8648,
    lng: 77.5993,
    baseRate: 30,
    tier: "Standard",
    totalSlots: 26,
    hasEVCharging: true,
    address: "Bannerghatta Main Rd, Bilekahalli, Bengaluru"
  },
  {
    id: "yeshwanthpur-junction",
    name: "Yeshwanthpur Transit Junction",
    area: "Yeshwanthpur",
    zone: "North-West Bangalore",
    lat: 13.0275,
    lng: 77.5432,
    baseRate: 25,
    tier: "Economy",
    totalSlots: 35,
    hasEVCharging: false,
    address: "Tumkur Rd, Yeshwanthpur, Bengaluru"
  },
  {
    id: "kr-puram-hanging-bridge",
    name: "KR Puram Station Bay",
    area: "KR Puram",
    zone: "East Bangalore",
    lat: 13.0050,
    lng: 77.6953,
    baseRate: 25,
    tier: "Economy",
    totalSlots: 28,
    hasEVCharging: false,
    address: "Old Madras Rd, KR Puram, Bengaluru"
  },
  {
    id: "old-airport-road-manipal",
    name: "Old Airport Road Tech Bay",
    area: "Old Airport Road",
    zone: "East Bangalore",
    lat: 12.9631,
    lng: 77.6473,
    baseRate: 35,
    tier: "Standard",
    totalSlots: 24,
    hasEVCharging: true,
    address: "HAL Old Airport Rd, Kodihalli, Bengaluru"
  },
  {
    id: "cunningham-road",
    name: "Cunningham Road Embassy Square",
    area: "Cunningham Road",
    zone: "Central Bangalore",
    lat: 12.9942,
    lng: 77.5983,
    baseRate: 50,
    tier: "Premium",
    totalSlots: 20,
    hasEVCharging: true,
    address: "Cunningham Rd, Vasanth Nagar, Bengaluru"
  }
];

module.exports = BANGALORE_AREAS;
